kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: srvcz-api-geospatial-staging
spec:
  selector:
    matchLabels:
      app: geospatial-service
      role: geospatial
  replicas: 1
  template:
    metadata:
      name: srvcz-api-deployment
      labels:
        app: geospatial-service
        role: geospatial
        env: staging
    spec:
      containers:
      - name: geospatial
        image: gcr.io/los-bidir/geospatial-api-app:master.1
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongodb_url
          - name: NODE_ENV
            value: staging
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8130
        ports:
        - name: geospatial
          containerPort: 8130
