apiVersion: v1
kind: Service
metadata:
  name: srvcz-geospatial-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8130
      targetPort: 8130
  selector:
    app: geospatial-service
    role: geospatial
